import http from 'node:http';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {deflateSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {PerspectiveCamera,Vector3} from '../vendor/three/build/three.module.js';
import {crc32,zipStore,unzipStore} from '../shared/archive.mjs';
import {validateShot,fitFrame,screenToImage,UndoHistory} from '../shared/document.mjs';
import {newWall,initialWorkspace,validateWorkspace,distance} from '../shared/workspace.mjs';
import {inspectGLB} from '../shared/model.mjs';
import {createEditorServer} from '../server.mjs';
function png(w=64,h=64){const chunk=(name,data)=>{const b=Buffer.alloc(12+data.length);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc32(b.subarray(4,8+data.length)),8+data.length);return b},head=Buffer.alloc(13);head.writeUInt32BE(w);head.writeUInt32BE(h,4);head[8]=8;head[9]=6;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',head),chunk('IDAT',deflateSync(Buffer.alloc(h*(w*4+1)))),chunk('IEND',Buffer.alloc(0))])}
function camera(){const c=new PerspectiveCamera(55,1,.05,2000);c.position.set(8,6,9);c.lookAt(0,0,0);c.updateMatrixWorld();return {position:c.position.toArray(),quaternion:c.quaternion.toArray(),fov:c.fov,near:c.near,far:c.far,aspect:c.aspect,projectionMatrix:c.projectionMatrix.toArray(),matrixWorld:c.matrixWorld.toArray()}}
function doc(asset){const workspace=initialWorkspace();return {format:'scribble-space-shot',version:1,id:crypto.randomUUID(),title:'Test view',note:'Keep the walkway clear.',scene:{id:'blank',revision:'sample-v1',sha256:createHash('sha256').update(JSON.stringify(workspace)).digest('hex')},workspace,capture:{asset,width:64,height:64},camera:camera(),marks:[],preview:null}}
test('ZIP round trip preserves binary and Unicode; detects alteration and traversal',async()=>{const zip=await zipStore({'manifest.json':'{"name":"café"}','assets/test.bin':new Uint8Array([0,255,42])}).arrayBuffer(),out=unzipStore(zip);assert.equal(new TextDecoder().decode(out['manifest.json']),' {"name":"café"}'.trim());assert.deepEqual([...out['assets/test.bin']],[0,255,42]);const bad=new Uint8Array(zip.slice(0));bad[45]^=1;assert.throws(()=>unzipStore(bad));assert.throws(()=>zipStore({'../secret':'x'}),/Unsafe/)});
test('restored camera reprojects the same world point; letterboxing preserves coordinates',()=>{const s=camera(),c=new PerspectiveCamera(s.fov,s.aspect,s.near,s.far);c.position.fromArray(s.position);c.quaternion.fromArray(s.quaternion);c.updateMatrixWorld();const p=new Vector3(0,0,0).project(c);assert.ok(Math.abs(p.x)<1e-12&&Math.abs(p.y)<1e-12);assert.deepEqual(screenToImage(400,250,fitFrame(800,500,640,640)),[.5,.5]);assert.deepEqual(c.matrixWorld.toArray(),s.matrixWorld)});
test('wall snap, precision and undo are independent from renderer',()=>{const w=newWall([.02,0,.01],[3.04,0,.01],{snap:.1});assert.equal(distance(w.a,w.b),3);assert.equal(w.precision,'snapped');const layout=initialWorkspace();layout.walls.push(w);validateWorkspace(layout);assert.throws(()=>validateWorkspace({...layout,walls:[{...w,height:-1}]}));const history=new UndoHistory();history.push([]);assert.deepEqual(history.undo([w]),[]);assert.equal(history.redo([])[0].height,3)});
test('invalid camera and marks are rejected before persistence',()=>{const d=doc('a'.repeat(64)+'.png');validateShot(d);assert.throws(()=>validateShot({...d,camera:{...d.camera,quaternion:[0,0,0,0]}}),/orientation/);assert.throws(()=>validateShot({...d,capture:{...d.capture,width:100}}),/aspect/);assert.throws(()=>validateShot({...d,marks:[{id:crypto.randomUUID(),type:'pen',color:'#000000',width:.01,points:[[1.2,0]]}]}),/coordinates/)});
test('model validation rejects external resources',()=>{const json=Buffer.from(JSON.stringify({asset:{version:'2.0'},images:[{uri:'https://example.com/private.png'}]}).padEnd(128,' ')),b=Buffer.alloc(20+json.length);b.writeUInt32LE(0x46546c67);b.writeUInt32LE(2,4);b.writeUInt32LE(b.length,8);b.writeUInt32LE(json.length,12);b.writeUInt32LE(0x4e4f534a,16);json.copy(b,20);assert.throws(()=>inspectGLB(b),/external/)});
test('local API saves images, enforces revisions and frozen camera, and keeps data private',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'scribble-test-'));const {server}=await createEditorServer({dataDir:root});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{const asset=await (await fetch(base+'/api/assets',{method:'POST',headers:{'Content-Type':'image/png'},body:png()})).json(),d=doc(asset.id);const put=(document,revision=null)=>fetch(base+'/api/shots/'+document.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({document,revision})});const r=await put(d);assert.equal(r.status,200);const saved=await r.json();assert.equal((await put(d)).status,409);const moved={...d,camera:{...d.camera,position:[1,2,3]}};assert.equal((await put(moved,saved.revision)).status,400);d.note='Add a desk.';const updated=await (await put(d,saved.revision)).json();assert.equal(updated.note,'Add a desk.');assert.equal(JSON.parse(await readFile(path.join(root,'shots',d.id+'.json'))).note,d.note);assert.equal((await fetch(base+'/data/shots/'+d.id+'.json')).status,404);assert.equal((await fetch(base+'/api/assets',{method:'POST',headers:{Origin:'https://evil.test','Content-Type':'image/png'},body:png()})).status,403);assert.equal(await new Promise((resolve,reject)=>{http.get(base+'/api/health',{headers:{Host:'evil.test'}},r=>{r.resume();resolve(r.statusCode)}).on('error',reject)}),403)}finally{await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true})}});
