import {readFile,writeFile,mkdir,copyFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),runtime=path.resolve(process.env.MCP_BUILD_RUNTIME||path.join(root,'mcp')),require=createRequire(path.join(runtime,'package.json')),esbuild=require('esbuild'),plugin=path.join(root,'plugins/scribble-space');
const built=await esbuild.build({entryPoints:[path.join(root,'mcp/server.mjs')],outfile:path.join(plugin,'scripts/mcp-server.mjs'),bundle:true,platform:'node',format:'esm',target:'node22',minify:true,metafile:true,legalComments:'none',nodePaths:[path.join(runtime,'node_modules')],external:['../app/*'],banner:{js:"import { createRequire as __createRequire } from 'node:module'; const require = __createRequire(import.meta.url);"}});
async function copyTree(src,dst){await mkdir(dst,{recursive:true});for(const entry of await readdir(src,{withFileTypes:true})){if(entry.name.startsWith('.'))continue;const a=path.join(src,entry.name),b=path.join(dst,entry.name);if(entry.isDirectory())await copyTree(a,b);else await copyFile(a,b)}}
await copyFile(path.join(root,'LICENSE'),path.join(plugin,'LICENSE'));
const app=path.join(plugin,'app');await mkdir(app,{recursive:true});for(const directory of ['public','shared','vendor','spec','docs','lib'])await copyTree(path.join(root,directory),path.join(app,directory));for(const file of ['editor.html','demo.html','README.md','LICENSE','THIRD-PARTY.md','server.mjs'])await copyFile(path.join(root,file),path.join(app,file));
const packages=new Map();for(const input of Object.keys(built.metafile.inputs)){let dir=path.dirname(path.resolve(input));while(dir!==path.dirname(dir)){try{const json=JSON.parse(await readFile(path.join(dir,'package.json'),'utf8'));if(json.name&&dir.includes('node_modules')){packages.set(json.name,{dir,...json});break}}catch{}dir=path.dirname(dir)}}
let notices='# Bundled MCP dependencies\n\n';const versions={};for(const [name,p]of [...packages].sort()){versions[name]=p.version;notices+=`## ${name} ${p.version}\n\n`;const license=(await readdir(p.dir)).find(n=>/^licen[cs]e(?:\..*)?$/i.test(n));notices+=license?await readFile(path.join(p.dir,license),'utf8'):`License: ${p.license}`;notices+='\n\n'}
await writeFile(path.join(plugin,'DEPENDENCIES.md'),notices);await writeFile(path.join(plugin,'build.json'),JSON.stringify({version:'0.1.0',dependencies:versions},null,2));console.log('Built standalone plugin runtime and dependency notices.');
